export default {
  ADD: 'ADD',
  REFRESH_ITEMS: 'REFRESH_ITEMS',
  FETCH_ITEMS_FROM_CACHE: 'FETCH_ITEMS_FROM_CACHE',
  ARCHIVE: 'ARCHIVE',
  UPDATE_UNCOUNT_LABEL: 'UPDATE_UNCOUNT_LABEL',
  UPDATE_ALARM_TIME: 'UPDATE_ALARM_TIME'
}
